# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=60, verbose_name='Nombre del producto')),
                ('existencia', models.IntegerField(verbose_name='Existencia en almacen')),
                ('defectos', models.IntegerField(verbose_name='Productos defectuosos')),
                ('pMayoreo', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Mayoreo')),
                ('pMedMay', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Medio Mayoreo')),
                ('pMenudeo', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Menudeo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Categoria')),
            ],
        ),
    ]
